# Generated by Django 4.2.6 on 2023-11-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_philomath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, unique=True, verbose_name='Course Name')),
                ('course_description', models.CharField(blank=True, max_length=100, verbose_name='Course Description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price')),
                ('course_picture', models.ImageField(blank=True, null=True, upload_to='media/course_pictures', verbose_name='Course Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_Name', models.CharField(max_length=30, unique=True, verbose_name='Question Name')),
                ('question_Description', models.CharField(max_length=100, verbose_name='Question Description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('isSolved', models.BooleanField(default=False, verbose_name='isSolved')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('DateofBirth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('isStudent', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media/profile_pictures', verbose_name='Profile Picture')),
                ('personal_Bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bio')),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.user')),
                ('Courses_bought', models.IntegerField(default=0, verbose_name='Course bought')),
                ('Quetions_asked', models.IntegerField(default=0, verbose_name='Quetions_asked')),
                ('Maximum_questions', models.IntegerField(default=3, verbose_name='Maximum_questions')),
                ('Courses', models.ManyToManyField(to='app1.course', verbose_name='Courses')),
            ],
            bases=('app1.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.user')),
                ('specialty', models.CharField(max_length=32, verbose_name='Specialty')),
                ('personal_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='rate')),
                ('numberofSudents', models.IntegerField(default=0)),
            ],
            bases=('app1.user',),
        ),
        migrations.DeleteModel(
            name='Philomath',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.AddField(
            model_name='student',
            name='Teacher',
            field=models.ManyToManyField(blank=True, null=True, to='app1.teacher'),
        ),
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.student'),
        ),
        migrations.AddField(
            model_name='question',
            name='solvedby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.teacher'),
        ),
    ]
