# Generated by Django 4.2.6 on 2023-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_philomath',
            field=models.BooleanField(blank=True, null=True, verbose_name='philomath status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_tutor',
            field=models.BooleanField(blank=True, null=True, verbose_name='tutor status'),
        ),
    ]
