# Generated by Django 4.2.6 on 2023-11-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_profile_tutor_field_alter_profile_is_philomath'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='question',
            field=models.CharField(default='There is nothing here Yet!', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tutor_field',
            field=models.CharField(default='Nothing yet!', max_length=50),
        ),
    ]
