# Generated by Django 4.2.6 on 2023-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_profile_question_alter_profile_tutor_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tutor_field',
            field=models.CharField(max_length=50),
        ),
    ]
