# Generated by Django 4.2.6 on 2023-11-06 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0014_alter_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='course_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
