# Generated by Django 4.2.6 on 2023-11-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_course_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='body',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='des',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
