# Generated by Django 4.2.6 on 2023-11-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_course_body_course_course_name_course_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='des',
            field=models.CharField(max_length=1000),
        ),
    ]
