# Generated by Django 4.2.6 on 2023-11-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_course_course_name_alter_course_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='images2/'),
        ),
    ]
