# Generated by Django 4.2.6 on 2023-11-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
