# Generated by Django 4.2.6 on 2023-11-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_course_course_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='question',
        ),
    ]
