# Generated by Django 4.2.6 on 2023-11-07 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0020_remove_profile_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Conctact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_email', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
