# Generated by Django 4.2.6 on 2023-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_course_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.FloatField(default=0.0),
        ),
    ]
